opsmanager:
  build: ops-manager/
  links:
  - database
  ports:
  - "8080:8080"
  - "8081:8081"
  volumes:
  - "/tmp/mms:/opt/mongodb/mms/logs/"

database:
  image: mongo:latest
  ports:
  - "27017:27017"

# database2:
#   image: mongo:latest
#   command: mongod --port 27018
#   ports:
#   - "27018:27018"
