opsmanager:
  build: ops-manager/
  links:
  - database
  ports:
  - "8080:8080"
  - "8081:8081"

database:
  image: mongo:latest
  ports:
  - "27017:27017"

dns:
  build: dns/
  ports:
  - "53:53/udp"
  privileged: true
  volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
